# Generated by Django 2.2.2 on 2019-06-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docentearea',
            options={'ordering': ['-da_id'], 'verbose_name': 'Docente Area', 'verbose_name_plural': 'Areas de los Docentes'},
        ),
    ]
