# Generated by Django 2.2.3 on 2019-09-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_auto_20190903_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='grupo_planta',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grupo_modo',
            field=models.CharField(default='servicio', max_length=50),
        ),
    ]
