# Generated by Django 2.2.3 on 2019-09-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_auto_20190903_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupo_modo',
            field=models.CharField(default='propio', max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grupo_planta',
            field=models.BooleanField(default=False),
        ),
    ]
