# Generated by Django 2.2.3 on 2019-11-22 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0010_auto_20191119_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupo_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.Componente'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grupo_planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.Planificacion'),
        ),
    ]
