# Generated by Django 2.2.3 on 2019-11-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0011_auto_20191122_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='grupo_asignado',
            field=models.BooleanField(default=False),
        ),
    ]
