# Generated by Django 2.2.3 on 2020-02-28 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('planificacion', '0012_auto_20200214_0334'),
        ('docentes', '0005_auto_20191102_0306'),
        ('componentes', '0014_auto_20191123_0328'),
        ('grupos', '0012_grupo_grupo_asignado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={
                ('grupo_numero', 'grupo_planificacion', 'grupo_docente', 'grupo_tipo', 'grupo_componente')},
        ),
    ]
