# Generated by Django 2.2.2 on 2019-06-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('facultad_nombre', models.CharField(max_length=50)),
                ('facultad_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
