# Generated by Django 2.2.2 on 2019-06-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultad',
            options={'ordering': ['-facultad_id'], 'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
    ]
