# Generated by Django 2.2.2 on 2019-06-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacion',
            options={'ordering': ['-planificacion_id'], 'verbose_name': 'Planificacion', 'verbose_name_plural': 'Planificaciones'},
        ),
    ]
