# Generated by Django 2.2.3 on 2019-09-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0007_auto_20190923_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacion',
            options={'ordering': ['-planificacion_anyo_lectivo', '-planificacion_semestre'], 'verbose_name': 'Planificacion', 'verbose_name_plural': 'Planificaciones'},
        ),
    ]
