# Generated by Django 2.2.3 on 2019-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0008_auto_20190923_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='planificacion_semestre',
            field=models.IntegerField(choices=[(1, 'Primero'), (2, 'Segundo')]),
        ),
    ]
