# Generated by Django 2.2.3 on 2019-09-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0009_auto_20190923_0816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planificacion',
            unique_together={('planificacion_anyo_lectivo', 'planificacion_semestre')},
        ),
    ]
