# Generated by Django 2.2.6 on 2020-02-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0011_auto_20191122_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='planificacion_anyo_lectivo',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2020),
        ),
    ]
