# Generated by Django 2.2.2 on 2019-06-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_de_estudio', '0001_initial'),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('componente_nombre', models.CharField(max_length=50)),
                ('componente_id', models.IntegerField(primary_key=True, serialize=False)),
                ('componente_chp', models.IntegerField(default=0)),
                ('componente_cht', models.IntegerField(default=0)),
                ('componente_ciclo', models.IntegerField(default=0)),
                ('componente_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Area')),
                ('componente_pde', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.PlanDeEstudio')),
            ],
        ),
    ]
