# Generated by Django 2.2.3 on 2019-10-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0003_auto_20190903_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='componente_credito',
            field=models.IntegerField(default=0),
        ),
    ]
