# Generated by Django 2.2.3 on 2019-11-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0005_auto_20191102_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='componente_ciclo',
            field=models.IntegerField(default=0),
        ),
    ]
