# Generated by Django 2.2.3 on 2019-11-22 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0010_auto_20191102_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='componente_pde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.PlanDeEstudio'),
        ),
    ]
