# Generated by Django 2.2.3 on 2019-11-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0013_auto_20191122_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='componente_nombre',
            field=models.CharField(max_length=100),
        ),
    ]
