# Generated by Django 2.2.7 on 2020-10-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0014_auto_20191123_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='componente_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.Area'),
        ),
    ]
