# Generated by Django 2.2.2 on 2019-06-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horario_id', models.IntegerField(primary_key=True, serialize=False)),
                ('horario_dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], default='Lunes', max_length=50)),
                ('horario_hora', models.CharField(choices=[('7', '7:00 am'), ('9', '9:00 am'), ('11', '11:00 am'), ('1', '1:00 pm'), ('3', '3:00 pm'), ('5', '5:00 pm')], default=7, max_length=10)),
                ('horario_vacio', models.BooleanField(default=True)),
                ('horario_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.Aula')),
                ('horario_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo')),
            ],
        ),
    ]
