# Generated by Django 2.2.2 on 2019-06-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
