# Generated by Django 2.2.2 on 2019-06-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_auto_20190619_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario_dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=50),
        ),
    ]
