# Generated by Django 2.2.2 on 2019-06-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
        ('aulas', '0001_initial'),
        ('horario', '0004_auto_20190619_1656'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('horario_dia', 'horario_hora', 'horario_grupo'), ('horario_dia', 'horario_hora', 'horario_aula', 'horario_grupo')},
        ),
    ]
