# Generated by Django 2.2.3 on 2019-08-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0006_auto_20190826_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={},
        ),
    ]
