# Generated by Django 2.2.3 on 2019-08-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0007_auto_20190826_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario_hora',
            field=models.IntegerField(choices=[(7, '7:00 am'), (9, '9:00 am'), (11, '11:00 am'), (13, '1:00 pm'), (15, '3:00 pm'), (17, '5:00 pm')], default=7),
        ),
    ]
