# Generated by Django 2.2.3 on 2020-03-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('horario', '0010_auto_20200228_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grupos.Grupo'),
        ),
    ]
