# Generated by Django 2.2.3 on 2020-03-14 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('horario', '0011_auto_20200304_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo'),
        ),
    ]
