# Generated by Django 2.2.3 on 2020-03-14 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('horario', '0012_auto_20200313_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo'),
        ),
    ]
