# Generated by Django 2.2.7 on 2020-09-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0013_auto_20200313_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='horario_vacio',
        ),
    ]
