# Generated by Django 2.2.7 on 2020-09-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0014_remove_horario_horario_vacio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='horario_vacio',
            field=models.BooleanField(default=True),
        ),
    ]
