# Generated by Django 2.2.4 on 2019-08-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0002_auto_20190619_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeestudio',
            name='pde_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
