# Generated by Django 2.2.3 on 2019-11-22 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0004_auto_20190903_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandeestudio',
            name='pde_anyo',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2019, verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='plandeestudio',
            name='pde_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.Carrera'),
        ),
    ]
