# Generated by Django 2.2.6 on 2020-02-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0006_auto_20200208_0229'),
        ('plan_de_estudio', '0006_auto_20200214_0334'),
    ]

    operations = [
    ]
