# Generated by Django 2.2.2 on 2019-06-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('carrera_nombre', models.CharField(max_length=50)),
                ('carrera_id', models.IntegerField(primary_key=True, serialize=False)),
                ('carrera_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamento.Departamento')),
            ],
        ),
    ]
