# Generated by Django 2.2.3 on 2019-11-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_auto_20190903_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='carrera_tipo',
            field=models.CharField(choices=[('p', 'Presencial'), ('v', 'Virtual')], default='p', max_length=1),
        ),
    ]
