# Generated by Django 2.2.3 on 2019-11-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0005_auto_20191122_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='carrera_tipo',
            field=models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], default='P', max_length=1),
        ),
    ]
