# Generated by Django 2.2.2 on 2019-06-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente_horas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docentehoras',
            options={'ordering': ['-dh_id'], 'verbose_name': 'Docente Hora', 'verbose_name_plural': 'Horas de los Docentes'},
        ),
    ]
