# Generated by Django 2.2.3 on 2019-09-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente_horas', '0004_auto_20190903_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docentehoras',
            old_name='dh_horas_asi',
            new_name='dh_horas_total',
        ),
        migrations.AddField(
            model_name='docentehoras',
            name='dh_horas_hor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docentehoras',
            name='dh_horas_planta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
