# Generated by Django 2.2.3 on 2019-11-19 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente_horas', '0005_auto_20190903_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentehoras',
            name='dh_horas_hor',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(48), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='docentehoras',
            name='dh_horas_planta',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='docentehoras',
            name='dh_horas_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
