# Generated by Django 2.2.2 on 2019-06-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('docente_nombre', models.CharField(max_length=50)),
                ('docente_id', models.IntegerField(primary_key=True, serialize=False)),
                ('docente_tipo_contrato', models.CharField(default='', max_length=50)),
                ('docente_inss', models.CharField(default='', max_length=50)),
                ('docente_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.Departamento')),
            ],
        ),
    ]
