# Generated by Django 2.2.3 on 2019-08-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_auto_20190719_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='docente_hname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
