# Generated by Django 2.2.3 on 2019-09-03 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_docente_docente_hname'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
