# Generated by Django 2.2.3 on 2019-11-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_auto_20190903_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='docente_tipo_contrato',
            field=models.CharField(choices=[('P', 'Planta'), ('H', 'Horario')], default='H', max_length=50),
        ),
    ]
