# Generated by Django 2.2.2 on 2019-06-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-area_id'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas de Clase'},
        ),
    ]
