# Generated by Django 2.2.3 on 2019-11-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_auto_20190903_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['area_nombre'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas de Clase'},
        ),
    ]
